version: "3"
services:
  backend:
    build: 
      context: ./backend
    environment:
      STORAGE: mysql
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DB: ${MYSQL_DB}
    networks: 
      - backend

  frontend:
    image: nginx:latest
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    labels:
      - "traefik.http.routers.projectopdracht_frontend.rule=Host(`s129173.devops-ap.be`)"
      - "traefik.http.routers.projectopdracht_frontend.tls=true"
      - "traefik.http.routers.projectopdracht_frontend.tls.certresolver=letsencrypt"
    networks: 
      - proxy
      - backend

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - backend

volumes:
  db-volume:

networks:
  proxy:
    external: true
    name: traefik
  backend:


