entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: s129173@ap.be
      storage: ssl-certs/acme.json
      httpChallenge:
        entryPoint: web
providers:
  docker:
    network: traefik
api:
  dashboard: true
